version: "3.3"

services:
  code-server:
    image: ghcr.io/linuxserver/code-server
    container_name: code-server
    volumes:
      - ./config:/config
      - /home/niklas:/home/niklas
      - /mnt/hdd1:/hdd
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/lib/docker/cli-plugins/docker-compose:/usr/lib/docker/cli-plugins/docker-compose
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ-Europe/Berlin 
    networks:
      - traefik-proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.code.rule=Host(`code.ntasler.de`)
      - traefik.http.routers.code.entrypoints=websecure
      - traefik.http.routers.code.middlewares=private-chain@file
      - traefik.http.services.code.loadbalancer.server.port=8443

networks:
  traefik-proxy:
    external: true
