---
version: "3.7"
services:
  mealie-frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-5
    container_name: mealie-frontend
    environment:
      - API_URL=http://mealie-api:9000
    restart: unless-stopped
    volumes:
      - ./data:/app/data/
    networks:
      - traefik-proxy
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.mealie.rule=Host(`mealie.ntasler.de`)
      - traefik.http.routers.mealie.entrypoints=websecure
      - traefik.http.services.mealie.loadbalancer.server.port=3000

  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-5
    container_name: mealie-api
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - ./data:/app/data/
    environment:
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.ntasler.de
    restart: unless-stopped
    networks:
      - default

networks:
  traefik-proxy:
    external: true
