services:
  authelia:
    container_name: authelia
    image: authelia/authelia:latest
    restart: unless-stopped
    volumes:
      - ./config:/config
    environment:
      TZ: "Europe/Berlin"
      PUID: 1000
      PGID: 1000
    labels:
      - traefik.enable=true
      - traefik.http.routers.authelia.rule=Host(`auth.ntasler.de`)
      - traefik.http.routers.authelia.entrypoints=websecure
      - traefik.http.routers.authelia.middlewares=public-chain@file
      - traefik.http.services.authelia.loadbalancer.server.port=9091
      - dockdns.name=auth.ntasler.de
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true
