version: '3.3'
services:
  vaultwarden:
    image: 'vaultwarden/server:latest'
    container_name: vaultwarden
    volumes:
      - './data/:/data/'
    labels:
      - traefik.enable=true
      - traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.ntasler.de`)
      - traefik.http.routers.vaultwarden.entrypoints=websecure
      - traefik.http.services.vaultwarden.loadbalancer.server.port=80
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true

