version: "3"

services:

  # WireGuard VPN service
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config:/config
    ports:
      - "51821:51821/udp"
    environment:
      - PUID=1000
      - PGID=1000
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wireguard-ui.rule=Host(`wg.nopshift.de`)"
      - "traefik.http.routers.wireguard-ui.entrypoints=websecure"
      - "traefik.http.routers.wireguard-ui.middlewares=private-chain@file"
      - "traefik.http.services.wireguard-ui.loadbalancer.server.port=5000"

  # WireGuard-UI service
  # wireguard-ui:
  #   image: ngoduykhanh/wireguard-ui:latest
  #   container_name: wireguard-ui
  #   restart: unless-stopped
  #   depends_on:
  #     - wireguard
  #   cap_add:
  #     - NET_ADMIN
  #   # Use the network of the 'wireguard' service
  #   # This enables to show active clients in the status page
  #   network_mode: service:wireguard
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./db:/app/db
  #     - ./config:/etc/wireguard

networks:
  traefik-proxy:
    external: true
