
services:
  db:
    image: mariadb:10.7
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    env_file:
      - db.env
    volumes:
      - ./db_data:/var/lib/mysql

  linkace:
    image: linkace/linkace:simple
    container_name: linkace
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./linkace.env:/app/.env
      - ./backups:/app/storage/app/backups
    labels:
      - traefik.enable=true
      - traefik.http.routers.linkace.rule=Host(`linkace.ntasler.de`)
      - traefik.http.routers.linkace.entrypoints=websecure
      - traefik.http.routers.linkace.middlewares=private-chain@file
      - traefik.http.services.linkace.loadbalancer.server.port=80
    networks:
      - default
      - traefik-proxy

networks:
  traefik-proxy:
    external: true
