version: "3.3"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    env_file:
      - gitea.env
    # environment variables defined in gitea.env
    # environment:
    # - GITEA__database__DB_TYPE=
    # - GITEA__database__HOST=
    # - GITEA__database__NAME=
    # - GITEA__database__USER=
    # - GITEA__database__PASSWD=
    # - USER_UID=
    # - USER_GID=
    # - DOMAIN=
    # - ROOT_URL=
    # - SSH_PORT=
    # - SSH_LISTEN_PORT=
    restart: unless-stopped
    networks:
      - traefik-proxy
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host(`git.ntasler.de`)
      - traefik.http.routers.gitea.entrypoints=websecure
      - traefik.http.routers.gitea.middlewares=private-chain@file
      - traefik.http.services.gitea.loadbalancer.server.port=3000

      - traefik.tcp.routers.gitea-ssh.entrypoints=gitea
      - traefik.tcp.routers.gitea-ssh.rule=HostSNI(`*`)
      - traefik.tcp.routers.gitea-ssh.service=gitea-ssh-svc
      - traefik.tcp.services.gitea-ssh-svc.loadbalancer.server.port=22
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
#    ports:
#      - 2222:22
    depends_on:
      - db

  db:
    image: postgres:13
    restart: unless-stopped
    env_file:
      - db.env
    # Variables defined in db.env:
    # POSTGRES_USER=
    # POSTGRES_DB=
    # POSTGRES_PASSWORD=    
    # POSTGRES_PASSWORD=
    volumes:
      - ./postgres:/var/lib/postgresql/data

networks:
  traefik-proxy:
    external: true
