version: "3.2"
services:
  ftp:
    image: stilliard/pure-ftpd:latest
    restart: unless-stopped
    container_name: ftp-paperless
    env_file:
      - ftp.env
    # environment: # variables defined in ftp.env:
    #  PUBLICHOST:
    #  FTP_USER_NAME:
    #  FTP_USER_PASS:
    #  FTP_USER_HOME:
    #  FTP_USER_UID:
    #  FTP_USER_GID:
    volumes:
      - /home/niklas/docker/paperless-ngx/consume:/home/ftp
    ports:
      - 21:21
    # Bind each passive ports to the host
      - 30000:30000
      - 30001:30001
      - 30002:30002
      - 30003:30003
      - 30004:30004
      - 30005:30005
      - 30006:30006
      - 30007:30007
      - 30008:30008
      - 30009:30009
