services:
  traefik:
    image: "traefik:v3.0"
    container_name: "traefik"
    restart: unless-stopped
    labels:
      - "logging.promtail=true"
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.rule=Host(`traefik.ntasler.de`)"
      - "traefik.http.routers.api.middlewares=private-chain@file"
      - "traefik.http.routers.api.service=api@internal"
    ports:
      - "443:443" # HTTPS
      - "80:80" # HTTP
    env_file:
      - traefik.env
    # Variables defined in traefik.env:
    # CF_API_EMAIL=
    # CF_API_KEY=
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./dynamic:/dynamic"
      - "./plugins:/plugins"
    networks:
      - traefik-proxy
    extra_hosts:
      - host.docker.internal:172.16.0.1

networks:
  traefik-proxy:
    external: true
