entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: ntasler.de
            sans: 
              - "*.ntasler.de"
  gitea:
    address: ":2222"

api:
  dashboard: true

providers:
  docker:
    exposedByDefault: false
    network: traefik-proxy
    defaultRule: Host(`{{ coalesce (index .Labels "com.docker.compose.service") (normalize .Name) }}.ntasler.de`)

certificatesResolvers:
  letsencrypt:
    acme:
      email: mail@ntasler.de
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare

log:
  level: WARN
