
services:
  microbin:
    image: danielszabo99/microbin:latest
    restart: unless-stopped
    volumes:
     - ./data:/app/microbin_data
    env_file:
      - .env
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.microbin.rule=Host(`microbin.ntasler.de`) || Host(`p.ntasler.de`)"
      - "traefik.http.routers.microbin.entrypoints=websecure"
      - "traefik.http.routers.microbin.middlewares=private-chain@file"
      - "traefik.http.services.microbin.loadbalancer.server.port=8080"

networks:
  traefik-proxy:
    external: true
