services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - ./configs:/app/data/configs
      - ./icons:/app/public/icons
      - ./images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.routers.homarr.rule=Host(`ntasler.de`)
      - traefik.http.routers.homarr.entrypoints=websecure
      - traefik.http.routers.homarr.middlewares=private-chain@file
      - traefik.http.services.homarr.loadbalancer.server.port=7575
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true
