version: "3.8"
services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: unless-stopped
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    ports:
      - 10.1.1.99:53:53/tcp
      - 10.1.1.99:53:53/udp
      - 10.1.1.99:853:853/tcp
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguard.rule=Host(`adguard.ntasler.de`)
      - traefik.http.routers.adguard.entrypoints=websecure
      - traefik.http.routers.adguard.middlewares=private-chain@file
      - traefik.http.services.adguard.loadbalancer.server.port=3000
    networks:
      - traefik-proxy
networks:
  traefik-proxy:
    external: true
