version: '3.7'
services:
  adguardhome:
      container_name: adguardhome
      restart: always
      volumes:
        - ./work:/opt/adguardhome/work
        - ./conf:/opt/adguardhome/conf
      ports:
        - 53:53/tcp
        - 53:53/udp
        - 67:67/udp
        - 68:68/tcp
        - 68:68/udp
        - 853:853/tcp
      labels:
        - traefik.enable=true
        - traefik.http.routers.adguard.rule=Host(`adguard.ntasler.de`)
        - traefik.http.routers.adguard.entrypoints=websecure
        - traefik.http.services.adguard.loadbalancer.server.port=3000
      image: adguard/adguardhome
      networks:
        - traefik-proxy

networks:
  traefik-proxy:
    external: true
