
services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    restart: unless-stopped
    privileged: true
    environment:
      - KASM_PORT=4433
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data:/opt
      - ./profiles:/profiles #optional
    labels:
      - traefik.enable=true
      - traefik.http.routers.kasm.rule=Host(`kasm.ntasler.de`)
      - traefik.http.routers.kasm.entrypoints=websecure
      - traefik.http.routers.kasm.middlewares=public-chain@file,authelia@file
      - traefik.http.services.kasm.loadbalancer.server.port=4433
      - traefik.http.services.kasm.loadbalancer.server.scheme=https
      - dockdns.name=kasm.ntasler.de
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true
