
services:
  linkding:
    container_name: linkding
    image: sissbruecker/linkding:latest
    volumes:
      - ./data:/etc/linkding/data
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.linkding.entrypoints=websecure
      - traefik.http.routers.linkding.rule=Host(`linkding.ntasler.de`)
      - traefik.http.routers.linkding.middlewares=private-chain@file
      - traefik.http.services.linkding.loadbalancer.server.port=9090
      - dockdns.name=test123.nopshift.de
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true
