services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    container_name: goaccess-frontend
    volumes:
      - ./web:/usr/share/nginx/html:ro 
    depends_on:
      - goaccess
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.goaccess.entrypoints=websecure"
      - "traefik.http.routers.goaccess.rule=Host(`goaccess.ntasler.de`)"
      - "traefik.http.routers.goaccess.middlewares=private-chain@file"
      - "traefik.http.services.goaccess.loadbalancer.server.port=80"

  goaccess:
    image: allinurl/goaccess
    container_name: goaccess-api
    restart: unless-stopped
    #      --log-format='%h %^[%d:%t %^] "%r" %s %b %R %u %^ %v %^ %Lms'
    command: > 
      /srv/logs/access.log
      -o /srv/report/index.html
      --real-time-html
      --origin=https://goaccess.ntasler.de
      --ws-url=wss://goaccess-backend.ntasler.de:443
      --log-format='{"ClientAddr":"%h:%^","DownstreamContentSize":"%b","Duration":"%T","OriginStatus":"%s","RequestAddr":"%v","RequestMethod":"%m","RequestPath":"%U","RequestProtocol":"%H","StartUTC":"%dT%t.%^"}'
      --time-format='%H:%M:%S'
      --date-format='%-%m-%d'
      --db-path=/srv/data
      --persist
      --restore
    volumes:
    - /home/niklas/docker/traefik/logs:/srv/logs:ro
    - ./web:/srv/report
    - ./goaccess_data:/srv/data
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.goaccess-backend.entrypoints=websecure"
      - "traefik.http.routers.goaccess-backend.rule=Host(`goaccess-backend.ntasler.de`)"
      - "traefik.http.services.goaccess-backend.loadbalancer.server.port=7890"

networks:
  traefik-proxy:
    external: true
