services:
  db_recipes:
    restart: always
    image: postgres:11-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - PGID=1000
      - PUID=1000

  web_recipes:
    restart: always
    image: vabene1111/recipes
    env_file:
      - .env
    environment:
      - PGID=1000
      - PUID=1000
    volumes:
      - ./staticfiles:/opt/recipes/staticfiles
      - ./nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    env_file:
      - .env
    environment:
      - PGID=1000
      - PUID=1000
    depends_on:
      - web_recipes
    volumes:
      - ./nginx_config:/etc/nginx/conf.d:ro
      - ./staticfiles:/static:ro
      - ./mediafiles:/media:ro
    networks:
      - default
      - traefik-proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.tandoor.rule=Host(`tandoor.ntasler.de`)
      - traefik.http.routers.tandoor.entrypoints=websecure
      - traefik.http.routers.tandoor.middlewares=private-chain@file
      - traefik.http.services.tandoor.loadbalancer.server.port=80

networks:
  traefik-proxy:
    external: true
